# Generated by Django 5.1.5 on 2025-02-09 17:23

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=detection.models.alert_image_path)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50)),
                ('alert_type', models.CharField(choices=[('fighting', 'Fighting'), ('vandalism', 'Vandalism'), ('assault', 'Assault'), ('camera_interference', 'Camera Interference'), ('suspicious_behavior', 'Suspicious Behavior')], default='suspicious_behavior', max_length=50)),
                ('metrics', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CameraLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emotion_data', models.JSONField(default=dict)),
                ('violence_data', models.JSONField(default=dict)),
            ],
        ),
    ]
