# Generated by Django 5.1.5 on 2025-02-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/'),
        ),
    ]
