# Generated by Django 5.1.5 on 2025-02-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('fighting', 'Fighting'), ('vandalism', 'Vandalism'), ('assault', 'Assault'), ('camera_interference', 'Camera Interference'), ('suspicious_behavior', 'Suspicious Behavior')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='cameralog',
            name='violence_data',
            field=models.JSONField(default=dict),
        ),
    ]
